language: php

php:
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

before_script:
  - mysql -e 'create database short;'
  - if [ $TRAVIS_BRANCH = 'master' ]; then wget $SERVICE_ACCOUNT -O resources/laravel-analytics/service-account-credentials.json; fi
  - if [ $TRAVIS_BRANCH = 'php5' ]; then wget $SERVICE_PKEY -O resources/laravel-analytics/privatekey.p12; fi

notifications:
  email:
    recipients:
      - killtw@gmail.com
    on_success: never
    on_failure: change

script:
  - vendor/bin/phpunit --coverage-text
