language: php

php:
  - 7.0

services:
  - mysql

matrix:
  fast_finish: true

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

before_script:
  - mysql -e 'create database short;'

notifications:
  email:
    recipients:
      - killtw@gmail.com
    on_failure: always

script:
  - vendor/bin/phpunit --coverage-text
