language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

before_script:
  - mysql -e 'create database short;'

notifications:
  email:
    recipients:
      - killtw@gmail.com
    on_success: always
    on_failure: always

script:
  - php artisan migrate
  - phpunit -c phpunit.xml --coverage-text
